# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Nick Zhang
title: Launch Engineer 
email: nick.zhang@shopify.com
website: www.github.com/zhangarang

# Social links
#twitter_username: facespics
github_username:  zhangarang
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: nick-zhang-b4663015b
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Nick and I’m a senior Launch Engineer at Shopify. What’s that you say? I provide technical guidance and solutions to enterprise level companies during both the pre/post sales process. 
  I am most skilled in: <mark>Not cracking under pressure</mark> and <mark>thinking outside the outside box</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in E-commerce and Technology, you can also find me doing the following:
   - Running down a ball in a <mark>squash</mark> court
   - Setting record low scores in video <mark>games</mark>
   - Creating <mark>gastronomic</mark> atrocities 
   - Taming <mark>cats</mark>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
